services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: gudang_db
      POSTGRES_USER: mesin_db
      POSTGRES_PASSWORD: P@sww0rd
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: gudang_webapp
    depends_on:
      - db
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  pgdata:
